export interface NgGridConfig {
    margins?:number[];
    draggable?:boolean;
    resizable?:boolean;
    max_cols?:number;
    max_rows?:number;
    visible_cols?:number;
    visible_rows?:number;
    min_cols?:number;
    min_rows?:number;
    col_width?:number;
    row_height?:number;
    cascade?:string;
    min_width?:number;
    min_height?:number;
    fix_to_grid?:boolean;
    auto_style?:boolean;
    auto_resize?:boolean;
    maintain_ratio?:boolean;
    prefer_new?:boolean;
}